export const DISPLAY_POKEMON_NAMES = "DISPLAY_POKEMON_NAMES";
export const SET_POKEMON_LIST = "SET_POKEMON_LIST";
export const GET_PREVIOUS_DETAILS = "GET_PREVIOUS_DETAILS";
export const GET_NEXT_DETAILS = "GET_NEXT_DETAILS";
export const GET_POKEMON_DETAILS = "GET_POKEMON_DETAILS";
export const SET_POKEMON_DATA = "SET_POKEMON_DATA";
export const GET_POKEMON_DETAILS_SUCCESS ="GET_POKEMON_DETAILS_SUCCESS";
export const CHANGE_POKEMON_NAMES = "CHANGE_POKEMON_NAMES"